#!/usr/bin/env python3
"""
CTB Confluence bootstrap and documentation upload.
Creates the CTB space if missing and uploads key CTB documents.
"""

from __future__ import annotations

import html
import os
from pathlib import Path

from atlassian import Confluence
from dotenv import load_dotenv


def load_env() -> None:
    load_dotenv()
    if not os.getenv("ATLASSIAN_URL"):
        load_dotenv(".env.local")


def require_env(*names: str) -> None:
    missing = [n for n in names if not os.getenv(n)]
    if missing:
        raise SystemExit(f"Missing environment variables: {', '.join(missing)}")


def ensure_space(confluence: Confluence, space_key: str, space_name: str) -> None:
    try:
        confluence.get_space(space_key)
        return
    except Exception:
        pass
    print(f"Creating Confluence space {space_key}...")
    confluence.create_space(space_key=space_key, space_name=space_name)


def upsert_page(confluence: Confluence, space: str, title: str, body: str, parent_id: str | None) -> str:
    page = None
    try:
        page = confluence.get_page_by_title(space=space, title=title)
    except Exception:
        page = None

    if page and page.get("id"):
        confluence.update_page(
            page_id=page["id"],
            title=title,
            body=body,
            parent_id=parent_id,
            representation="storage",
        )
        return page["id"]

    created = confluence.create_page(
        space=space,
        title=title,
        body=body,
        parent_id=parent_id,
        representation="storage",
    )
    return created["id"]


def read_doc(path: Path) -> str:
    content = path.read_text(encoding="utf-8")
    return f"<pre>{html.escape(content)}</pre>"


def main() -> None:
    load_env()
    require_env("ATLASSIAN_URL", "ATLASSIAN_EMAIL", "ATLASSIAN_API_TOKEN")

    base_url = os.getenv("ATLASSIAN_URL").rstrip("/")
    space_key = os.getenv("CONFLUENCE_SPACE", "CTB")
    space_name = os.getenv("CONFLUENCE_SPACE_NAME", "CTB")

    confluence = Confluence(
        url=f"{base_url}/wiki",
        username=os.getenv("ATLASSIAN_EMAIL"),
        password=os.getenv("ATLASSIAN_API_TOKEN"),
        cloud=True,
    )

    ensure_space(confluence, space_key, space_name)

    docs_root = Path(
        os.getenv(
            "CTB_DOCS_DIR",
            "/Users/carlosa/00-PROJECTS/CTB/client-repos/main/docs/md",
        )
    )

    documents = [
        ("CTB - Analisis Proyecto", docs_root / "ANALISIS-PROYECTO-CTB.md"),
        ("CTB - Requisitos", docs_root / "CTB-REQUISITOS-ANALISIS.md"),
        ("CTB - Plan de Pruebas", docs_root / "plan-pruebas-ctb.md"),
        ("CTB - Reporte Inicial", docs_root / "reporte-inicial-ctb.md"),
        ("CTB - Reporte Ejecucion", docs_root / "reporte-ejecucion-ctb.md"),
        ("CTB - Reporte Ejecucion 2026-01-12", docs_root / "REPORTE-EJECUCION-CTB-2026-01-12.md"),
        ("CTB - Evidencias y Flujo", docs_root / "FLUJO-DOCUMENTACION-EVIDENCIAS.md"),
    ]

    root_title = os.getenv("CTB_CONFLUENCE_ROOT", "CTB - Documentacion")
    root_body = "<p>CTB documentation index generated by HAIDA automation.</p>"
    root_id = upsert_page(confluence, space_key, root_title, root_body, None)

    for title, path in documents:
        if not path.exists():
            print(f"Skipping missing doc: {path}")
            continue
        body = read_doc(path)
        upsert_page(confluence, space_key, title, body, root_id)
        print(f"Uploaded: {title}")

    print(f"Done. Space: {space_key}")


if __name__ == "__main__":
    main()
